#!/bin/sh

set -- $(dimensions)
w=$(echo "$1 - 2" | bc)
x=$(( $1 / 2 - $w / 2 ))
y=$(( $2 / 5 ))
h=$(( $2 / 50 ))
font="crisp:size=12:antialias=true:autohint=true"

URL="https://duckduckgo.com/?q="
QUERY=$(echo '' | dmenu -p "Web Search:" -i -f)
if [ -n "$QUERY" ]; then
	$BROWSER --new-window "${URL}${QUERY}"
fi
