#!/bin/sh

read -p "1 - Full, 2 - Delay(5), 0 - Crop: " scr_scrot
if [[ $scr_scrot == 0 ]]; then
	scrot -s -e 'mv $f ~/Pictures/screenshots; viewnior ~/Pictures/screenshots/$f'
elif [[ $scr_scrot == 1 ]]; then
	scrot -e 'mv $f ~/Pictures/screenshots; viewnior ~/Pictures/screenshots/$f'
elif [[ $scr_scrot == 2 ]]; then
	scrot -d 5 -e 'mv $f ~/Pictures/screenshots; viewnior ~/Pictures/screenshots/$f'
fi
