#!/bin/sh

mute() { amixer sset Master toggle ;}
up() { amixer sset Master 5%+ unmute ;}
down() { amixer sset Master 5%- unmute ;}

case "$1" in
	mute) mute ;;
	up) up ;;
	down) down ;;
esac >/dev/null

pkill -RTMIN+10 dwmblocks &
